---
# tasks file for jinopl.aws-web-server
- name: Run when os is redhat family
  include_tasks: rhel.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Run when os Debian family
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"