---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install dependencies (RedHat).
      yum:
        name:
          - cronie
          - epel-release
        state: present
      when: ansible_os_family == 'RedHat'

  roles:
    - jinopl.aws-web-server